#!/bin/bash
export QT_QPA_PLATFORMTHEME=kde

# for Chinese
#export LANGUAGE=zh_CN.UTF-8
#export LANG=zh_CN.UTF-8
#export LC_ALL=zh_CN.UTF-8

exec lxpanel &
exec spacefm --desktop &
exec openbox-session
